USE [quan_ly_tu_nhan]
GO 

INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'01', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'02', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'03', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'04', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'05', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'06', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'07', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'08', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'09', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'10', N'1')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'11', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'12', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'13', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'14', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'15', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'16', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'17', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'18', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'19', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'20', N'2')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'21', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'22', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'23', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'24', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'25', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'26', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'27', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'28', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'29', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'30', N'3')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'31', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'32', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'33', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'34', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'35', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'36', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'37', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'38', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'39', N'4')
INSERT [dbo].[Prisoner_with_Prison] ([prisoner_id], [prison_id]) VALUES (N'40', N'4')
GO 




